# Running this docker image runs the integration tests.
FROM golang:1.27.1@sha256:512690a5660563b57d37ecc31129e7f136e831db2aed24a1dbeb8ad7380dc0fa

RUN apt-get update -y && apt-get install sudo stunnel4 redis memcached -y && rm -rf /var/lib/apt/lists/*

WORKDIR /workdir

ENV GOPROXY=https://proxy.golang.org
COPY go.mod go.sum /workdir/
RUN go mod download

COPY Makefile /workdir
RUN make bootstrap

COPY src /workdir/src
COPY test /workdir/test
CMD make tests_with_redis
