# === COMMON TEMPLATES ===
job-defaults: &job-defaults
  working_directory: &working_directory
                       ~/rate-limit
  environment:
    AWS_DEFAULT_REGION: us-west-2
    AWS_REGION: us-west-2

machine-setup: &machine-setup
  machine:
    image: ubuntu-2204:2023.10.1

setup-env: &setup-env
  run:
    name: Setup Environment
    command: |
      ./ops/env.sh
      echo 'unset AWS_ACCESS_KEY_ID' >> $BASH_ENV
      echo 'unset AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
      echo 'export AWS_ACCOUNT_ID=$AWS_PRESIDIO_VAULT_ACCOUNT_ID' >> $BASH_ENV
      echo 'export AWS_REGION=us-east-1' >> $BASH_ENV
      echo 'export VERSION=${CIRCLE_TAG:-test-$CIRCLE_SHA1}' >> $BASH_ENV

persist-workspace: &persist-workspace
  persist_to_workspace:
    root: .
    paths: "*"

attach-workspace: &attach-workspace
  attach_workspace:
    at: *working_directory

# === JOBS ===
version: 2.1
jobs:
  build:
    <<: *machine-setup
    <<: *job-defaults
    steps:
      - checkout
      - <<: *setup-env
      - run:
          name: Build
          command: docker-compose run build
      - run:
          name: Docker image build
          command: |
            ./ops/docker-login.sh
            docker-compose build ratelimit
            ./ops/docker-save.sh
      - <<: *persist-workspace

  deploy:
    <<: *machine-setup
    <<: *job-defaults
    steps:
      - <<: *attach-workspace
      - <<: *setup-env
      - run:
          name: Docker push
          command: |
            ./ops/docker-login.sh
            ./ops/docker-load.sh
            docker-compose push

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          context:
            - circleci
            - aws-accounts
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          context:
            - circleci
            - aws-accounts
          requires:
            - build
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
