version: 2
job-defaults: &job-defaults
  working_directory: &working_directory
    /go/src/github.com/lyft/ratelimit/

persist-workspace: &persist-workspace
  persist_to_workspace:
    root: /go/src/github.com/lyft/ratelimit/
    paths: "*"

attach-workspace: &attach-workspace
  attach_workspace:
    at: *working_directory

jobs:
  test:
    <<: *job-defaults
    docker:
      - image: circleci/golang:1.9
      - image: redis:alpine
    steps:
      - checkout
      - run:
          command: |
            make test

  build:
    <<: *job-defaults
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Compile
          command: |
            make bootstrap
            make compile
      - run:
          name: Build Docker Image
          command: |
            make docker

workflows:
  version: 2
  test_and_build:
    jobs:
      - build
      - test
