---
domain: mongo_cps
descriptors:
  - key: database
    value: users
    rate_limit:
      unit: minute
      requests_per_unit: 5

  - key: database
    value: default
    rate_limit:
      unit: minute
      requests_per_unit: 5
