#!/bin/bash

PROTOC_VER=3.5.1
PROTOC_REL=protoc-"${PROTOC_VER}"-linux-x86_64.zip
pushd /tmp
wget https://github.com/google/protobuf/releases/download/v"${PROTOC_VER}/${PROTOC_REL}"
unzip "${PROTOC_REL}" -d protoc
popd

mkdir -p bin
mv /tmp/protoc bin/protoc
go build -o bin/protoc-gen-go ./vendor/github.com/golang/protobuf/protoc-gen-go
