name: Build and push to ACR

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push Docker image to ACR
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
      
      - name: Log in to Azure ACR
        uses: docker/login-action@v1.10.0
        with:
          registry: plandaycontainers.azurecr.io
          username: ${{ secrets.ACRID }}
          password: ${{ secrets.ACRPASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: plandaycontainers.azurecr.io/envoy-rate-limit:0.0.{{ github.run_number }}
          file: Dockerfile